### ISSUE TITLE
Error on new license request

### ISSUE THREAD

**Issue by freegovinfo** [spdx/spdx-online-tools#294]
I just tried to submit a new license via https://tools.spdx.org/app/submit_new_license/ and got the following error> Please advise.

Unexpected error, please email the SPDX technical workgroup that the following error has occurred: Traceback (most recent call last): File "/spdx/src/app/views.py", line 172, in submitNewLicense statusCode = utils.createIssue(licenseAuthorName, licenseName, licenseIdentifier, licenseComments, licenseSourceUrls, licenseHeader, licenseOsi, licenseExamples, licenseRequestUrl, token, urlType) File "/spdx/src/app/utils.py", line 340, in createIssue body = "**1.** License Name: {0}\n**2.** Short identifier: {1}\n**3.** License Author or steward: {2}\n**4.** Comments: {3}\n**5.** Standard License Header: {4}\n**6.** License Request Url: {5}\n**7.** URL(s): {6}\n**8.** OSI Status: {7}\n**9.** Example Projects: {8}".format(licenseName, licenseIdentifier, licenseAuthorName, licenseComments, licenseHeader, licenseRequestUrl, licenseUrls, licenseOsi, licenseExampleUrls) UnicodeEncodeError: 'ascii' codec can't encode character u'\xa7' in position 134: ordinal not in range(128)

**Comment by jlovejoy** [comment]
@goneall - is this still an open issue?

**Comment by goneall** [comment]
@jlovejoy I believe this is still an open issue.  As @rtgdk noted above, this is a good first issue for someone to tackle.

**Comment by BassCoder2808** [comment]
Hi @goneall , I would be happy to contribute to this, if this issue is still open, can you please guide me through this like what needs to be changed, it would be really helpful

**Comment by jlovejoy** [comment]
@goneall - I think we have fixed this.. or at least it was working last time I used it. 

@BassCoder2808 - in the meantime, if you want to "test" the submission tool, I think that would be a great way to familiarize yourself with the user experience (and see if you get an error). It's fine to submit a "fake/test" license - we can remove it later. There are some instructions related to the overall process, that might also be good to have a look at for context: https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md

Thanks!

**Comment by goneall** [comment]
@jlovejoy - I think this is still an issue - it has to do with the text being encoded differently which you haven't experienced.

@freegovinfo - do you have some text which duplicates this problem?  If so, could you attach it to a comment.

**Comment by jlovejoy** [comment]
@BassCoder2808 - are you still working on this one?

**Comment by BassCoder2808** [comment]
Hi @jlovejoy no actually, I thought that this issue was closed also is there a way to duplicate this issue if this is occurring again?

**Comment by goneall** [comment]
Based on the above comments, I'm going to close this issue - if it happens again, we can create a new issue
