### ISSUE TITLE
Remove standard license header field in created issue for new license submission

### ISSUE THREAD

**Issue by jlovejoy** [spdx/spdx-online-tools#452]
when we updated the submission form fields, we did not also update the display to no longer show 
the  Standard License Header field even tho that is no longer asked in the submission form

It might be nice to add a link to the corresponding Github issue

**Comment by BassCoder2808** [comment]
Hi @jlovejoy, I would like to work on this issue, can you please help me with how can I get started with it and what all fields need to be updated?

**Comment by jlovejoy** [comment]
@BassCoder2808  the submission form does not ask for a Standard License Header any longer, but once submitted, the license request page still includes the Standard License Header field, see for example https://tools.spdx.org/app/license_requests/213/ 

We need to remove the Standard License Header field from the license request template. 

does that make sense?

**Comment by BassCoder2808** [comment]
Ok yes, I have understood the issue now, so now instead of that, we will put the github issue link. Thanks @jlovejoy I will update my PR and will let you know once its done

**Comment by BanulaKumarage** [comment]
> @BassCoder2808 the submission form does not ask for a Standard License Header any longer, but once submitted, the license request page still includes the Standard License Header field, see for example https://tools.spdx.org/app/license_requests/213/
> 
> We need to remove the Standard License Header field from the license request template.
> 
> does that make sense?

@jlovejoy was there a specific purpose for putting the standard license header earlier on the license information page? Was it asked from the user earlier?

**Comment by jlovejoy** [comment]
@BanulaKumarage yes, it used to be asked for in the submission form, but it is not something that is used in very many licenses, and in the unlikely case that it is used, someone from SPDX-legal needs to really look at it and probably code it in the XML manually. So we decided it wasn't necessary to ask and removed from the submission form

**Comment by BanulaKumarage** [comment]
> @BanulaKumarage yes, it used to be asked for in the submission form, but it is not something that is used in very many licenses, and in the unlikely case that it is used, someone from SPDX-legal needs to really look at it and probably code it in the XML manually. So we decided it wasn't necessary to ask and removed from the submission form

Thank you @jlovejoy I got the idea.

**Comment by jlovejoy** [comment]
@BassCoder2808 - has this been solved/merged? looks like there may be 2 PRs?

**Comment by BassCoder2808** [comment]
Hi @jlovejoy actually there has been some miscommunications like there are 2 issues and 2 PRs that solve the 2 issues separately which in the end intend to do the same task.
So what I feel is that we can move forward with this one (just because it was opened earlier and solves one more issue)
and the PR to move forward with #456

**Comment by goneall** [comment]
@BassCoder2808 - I merged in PR #450 which seems to have caused a merge conflict for #456 - If you could resolve and address the comments from @rtgdk I'll merge it in for the next release.

**Comment by jlovejoy** [comment]
the standard license header field is still showing up in the list of submitted licenses in the online, see https://tools.spdx.org/app/license_requests/251/

but it is not listed in the Github issue https://github.com/spdx/license-list-XML/issues/2033

**Comment by BassCoder2808** [comment]
Hi @jlovejoy yes I have checked the code even though the previous PR is not merged till now, but once that get's merged I will make the changes, so the problem is in `license_information.html` wherein we have not removed the standard license header field even though in code we have removed it

**Comment by goneall** [comment]
@BassCoder2808 @jlovejoy - Checking to see if this is resolved or if it should be left open

**Comment by BassCoder2808** [comment]
This issue has been solved @goneall as far as I remember
